[workspace]
authors = ["Nick Russo <nijaru7@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "conda-forge"]
name = "omendb-vector"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = "==1.0.0b1"
pytest = ">=9.1.1,<10"
ruff = ">=0.16.2,<0.17"
python = ">=3.14,<3.15"
uv = ">=0.12.3,<0.13"
